CREATE TABLE Musteri(
mid INT NOT NULL PRIMARY KEY,
mad VARCHAR(50),
telefon VARCHAR(15),
mail VARCHAR(20))
CREATE TABLE Satýs(
sid INT NOT NULL PRIMARY KEY,
bilet_no INT NOT NULL,
tarih VARCHAR(10),
zaman VARCHAR(20),
sýnýf VARCHAR(15))
CREATE TABLE Urun(
uid INT NOT NULL PRIMARY KEY ,
uad VARCHAR(50) ,
fiyat VARCHAR(15),
açýklama VARCHAR(250),
tarif VARCHAR(250))
CREATE TABLE Kategori(
kid INT NOT NULL PRIMARY KEY,
kad VARCHAR(50))
CREATE TABLE Firma(
fid INT NOT NULL PRIMARY KEY,
fad VARCHAR(50),
fadres VARCHAR(250),
ftelefon VARCHAR(15))
CREATE TABLE Teslim(
tid INT NOT NULL PRIMARY KEY,
kalkýþ VARCHAR(20),
kalkýþ_zamaný VARCHAR(20),
varýþ VARCHAR(20))
CREATE TABLE Odeme(
oid INT NOT NULL PRIMARY KEY,
nakit_ode VARCHAR(15),
net_fiyat VARCHAR(15))